"""Add processed_filename and processed_filepath fields

Revision ID: 17a27f26bffb
Revises: 501c934610b9
Create Date: 2025-02-25 22:21:20.948659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a27f26bffb'
down_revision = '501c934610b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processed_filepath', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('processed_filepath')
        batch_op.drop_column('processed_filename')

    # ### end Alembic commands ###
