-- EduMind managed MySQL schema
-- Generated by backend_fastapi/scripts/init_db.py

CREATE DATABASE IF NOT EXISTS `edumind` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `edumind`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Drop table: note_timestamps

DROP TABLE IF EXISTS note_timestamps;

-- Drop table: subtitles

DROP TABLE IF EXISTS subtitles;

-- Drop table: questions

DROP TABLE IF EXISTS questions;

-- Drop table: notes

DROP TABLE IF EXISTS notes;

-- Drop table: videos

DROP TABLE IF EXISTS videos;

-- Drop table: users

DROP TABLE IF EXISTS users;

-- Create table: users

CREATE TABLE users (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(64) NOT NULL,
	email VARCHAR(120),
	phone VARCHAR(32),
	password_hash VARCHAR(255) NOT NULL,
	password_fingerprint VARCHAR(64),
	created_at DATETIME NOT NULL,
	last_login DATETIME,
	login_count INTEGER NOT NULL DEFAULT '0',
	gender VARCHAR(10),
	education VARCHAR(50),
	occupation VARCHAR(50),
	learning_direction VARCHAR(100),
	avatar VARCHAR(255),
	bio TEXT,
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_password_fingerprint ON users (password_fingerprint);
CREATE UNIQUE INDEX ix_users_phone ON users (phone);
CREATE UNIQUE INDEX ix_users_username ON users (username);

-- Create table: videos

CREATE TABLE videos (
	id INTEGER NOT NULL AUTO_INCREMENT,
	title VARCHAR(255),
	filename VARCHAR(255),
	filepath VARCHAR(255),
	url VARCHAR(255),
	md5 VARCHAR(32),
	processed_filename VARCHAR(255),
	processed_filepath VARCHAR(255),
	preview_filename VARCHAR(255),
	preview_filepath VARCHAR(255),
	subtitle_filepath VARCHAR(255),
	status ENUM('UPLOADED','PENDING','PROCESSING','COMPLETED','FAILED','DOWNLOADING') NOT NULL,
	error_message TEXT,
	upload_time DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	process_progress FLOAT NOT NULL,
	current_step VARCHAR(255),
	task_id VARCHAR(255),
	duration FLOAT,
	fps FLOAT,
	width INTEGER,
	height INTEGER,
	frame_count INTEGER,
	summary TEXT,
	tags TEXT,
	PRIMARY KEY (id)
);

-- Create table: notes

CREATE TABLE notes (
	id INTEGER NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	content_vector TEXT,
	note_type VARCHAR(50) NOT NULL,
	video_id INTEGER,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	tags VARCHAR(255),
	keywords VARCHAR(500),
	PRIMARY KEY (id),
	FOREIGN KEY(video_id) REFERENCES videos (id)
);

-- Create table: questions

CREATE TABLE questions (
	id INTEGER NOT NULL AUTO_INCREMENT,
	video_id INTEGER,
	content TEXT NOT NULL,
	answer TEXT,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(video_id) REFERENCES videos (id)
);

-- Create table: subtitles

CREATE TABLE subtitles (
	id INTEGER NOT NULL AUTO_INCREMENT,
	video_id INTEGER NOT NULL,
	start_time FLOAT NOT NULL,
	end_time FLOAT NOT NULL,
	text TEXT NOT NULL,
	source VARCHAR(50) NOT NULL,
	language VARCHAR(10) NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(video_id) REFERENCES videos (id)
);

-- Create table: note_timestamps

CREATE TABLE note_timestamps (
	id INTEGER NOT NULL AUTO_INCREMENT,
	note_id INTEGER NOT NULL,
	time_seconds FLOAT NOT NULL,
	subtitle_text TEXT,
	created_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(note_id) REFERENCES notes (id)
);

SET FOREIGN_KEY_CHECKS = 1;
