"""Update note model for similarity features

Revision ID: 07b410815098
Revises: b27c00ab4130
Create Date: 2025-03-31 13:47:16.590402

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '07b410815098'
down_revision = 'b27c00ab4130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_vector', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('note_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=500), nullable=True))
        batch_op.alter_column('content', existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column('markdown_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markdown_content', sa.TEXT(), nullable=True))
        batch_op.alter_column('content', existing_type=sa.TEXT(), nullable=True)
        batch_op.drop_column('keywords')
        batch_op.drop_column('note_type')
        batch_op.drop_column('content_vector')

    # ### end Alembic commands ###
