"""Add video preview and info fields

Revision ID: 4621b2013024
Revises: 17a27f26bffb
Create Date: 2025-02-25 22:29:45.171636

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4621b2013024'
down_revision = '17a27f26bffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('preview_filepath', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('preview_filepath')
        batch_op.drop_column('preview_filename')

    # ### end Alembic commands ###
