"""add subtitle_filepath field

Revision ID: 77f3bdba655b
Revises: fd5bc064a9e2
Create Date: 2025-02-27 14:44:10.108595

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '77f3bdba655b'
down_revision = 'fd5bc064a9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle_filepath', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('subtitle_filepath')

    # ### end Alembic commands ###
