"""允许问题表中video_id为空

Revision ID: b27c00ab4130
Revises: ee7d2fcea35b
Create Date: 2025-03-21 15:37:30.078822

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b27c00ab4130'
down_revision = 'ee7d2fcea35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('video_id', existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('video_id', existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
