"""add md5 field to video model

Revision ID: ee7d2fcea35b
Revises: cad8c56cbe5f
Create Date: 2025-03-03 20:13:29.153744

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ee7d2fcea35b'
down_revision = 'cad8c56cbe5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('md5', sa.String(length=32), nullable=True))
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum(
                'UPLOADED', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'DOWNLOADING', name='videostatus'
            ),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'current_step', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=True
        )
        batch_op.alter_column('task_id', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('task_id', existing_type=sa.String(length=255), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column(
            'current_step', existing_type=sa.String(length=255), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum(
                'UPLOADED', 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'DOWNLOADING', name='videostatus'
            ),
            type_=sa.VARCHAR(length=10),
            existing_nullable=True,
        )
        batch_op.drop_column('md5')

    # ### end Alembic commands ###
