"""Add subtitles table

Revision ID: fd5bc064a9e2
Revises: 4621b2013024
Create Date: 2025-02-25 22:31:48.601632

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fd5bc064a9e2'
down_revision = '4621b2013024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_edited')
        batch_op.drop_column('original_text')
        batch_op.drop_column('edited_by')
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('edited_by', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('original_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_edited', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
